# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ele_bak.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1184, 913)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_1 = QtGui.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(90, 30, 100, 500))
        self.frame_1.setFrameShape(QtGui.QFrame.Box)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line = QtGui.QFrame(self.frame_1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.line_2 = QtGui.QFrame(self.frame_1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.line_3 = QtGui.QFrame(self.frame_1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.line_4 = QtGui.QFrame(self.frame_1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.line_5 = QtGui.QFrame(self.frame_1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.line_6 = QtGui.QFrame(self.frame_1)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.line_43 = QtGui.QFrame(self.frame_1)
        self.line_43.setFrameShape(QtGui.QFrame.HLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.verticalLayout.addWidget(self.line_43)
        self.line_31 = QtGui.QFrame(self.frame_1)
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.verticalLayout.addWidget(self.line_31)
        self.line_44 = QtGui.QFrame(self.frame_1)
        self.line_44.setFrameShape(QtGui.QFrame.HLine)
        self.line_44.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_44.setObjectName(_fromUtf8("line_44"))
        self.verticalLayout.addWidget(self.line_44)
        self.splitter_1 = QtGui.QSplitter(self.centralwidget)
        self.splitter_1.setGeometry(QtCore.QRect(90, 720, 80, 80))
        self.splitter_1.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_1.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_1.setLineWidth(1)
        self.splitter_1.setMidLineWidth(0)
        self.splitter_1.setOrientation(QtCore.Qt.Vertical)
        self.splitter_1.setObjectName(_fromUtf8("splitter_1"))
        self.EleButton1Up = QtGui.QPushButton(self.splitter_1)
        self.EleButton1Up.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton1Up.setFont(font)
        self.EleButton1Up.setObjectName(_fromUtf8("EleButton1Up"))
        self.EleButton1Down = QtGui.QPushButton(self.splitter_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton1Down.setFont(font)
        self.EleButton1Down.setObjectName(_fromUtf8("EleButton1Down"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(190, 30, 100, 650))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.line_45 = QtGui.QFrame(self.frame_2)
        self.line_45.setFrameShape(QtGui.QFrame.HLine)
        self.line_45.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_45.setObjectName(_fromUtf8("line_45"))
        self.verticalLayout_2.addWidget(self.line_45)
        self.line_46 = QtGui.QFrame(self.frame_2)
        self.line_46.setFrameShape(QtGui.QFrame.HLine)
        self.line_46.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_46.setObjectName(_fromUtf8("line_46"))
        self.verticalLayout_2.addWidget(self.line_46)
        self.line_32 = QtGui.QFrame(self.frame_2)
        self.line_32.setFrameShape(QtGui.QFrame.HLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.verticalLayout_2.addWidget(self.line_32)
        self.line_47 = QtGui.QFrame(self.frame_2)
        self.line_47.setFrameShape(QtGui.QFrame.HLine)
        self.line_47.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_47.setObjectName(_fromUtf8("line_47"))
        self.verticalLayout_2.addWidget(self.line_47)
        self.line_48 = QtGui.QFrame(self.frame_2)
        self.line_48.setFrameShape(QtGui.QFrame.HLine)
        self.line_48.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_48.setObjectName(_fromUtf8("line_48"))
        self.verticalLayout_2.addWidget(self.line_48)
        self.line_49 = QtGui.QFrame(self.frame_2)
        self.line_49.setFrameShape(QtGui.QFrame.HLine)
        self.line_49.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_49.setObjectName(_fromUtf8("line_49"))
        self.verticalLayout_2.addWidget(self.line_49)
        self.line_50 = QtGui.QFrame(self.frame_2)
        self.line_50.setFrameShape(QtGui.QFrame.HLine)
        self.line_50.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_50.setObjectName(_fromUtf8("line_50"))
        self.verticalLayout_2.addWidget(self.line_50)
        self.line_51 = QtGui.QFrame(self.frame_2)
        self.line_51.setFrameShape(QtGui.QFrame.HLine)
        self.line_51.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_51.setObjectName(_fromUtf8("line_51"))
        self.verticalLayout_2.addWidget(self.line_51)
        self.line_52 = QtGui.QFrame(self.frame_2)
        self.line_52.setFrameShape(QtGui.QFrame.HLine)
        self.line_52.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_52.setObjectName(_fromUtf8("line_52"))
        self.verticalLayout_2.addWidget(self.line_52)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(300, 30, 100, 650))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.line_53 = QtGui.QFrame(self.frame_3)
        self.line_53.setFrameShape(QtGui.QFrame.HLine)
        self.line_53.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_53.setObjectName(_fromUtf8("line_53"))
        self.verticalLayout_3.addWidget(self.line_53)
        self.line_54 = QtGui.QFrame(self.frame_3)
        self.line_54.setFrameShape(QtGui.QFrame.HLine)
        self.line_54.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_54.setObjectName(_fromUtf8("line_54"))
        self.verticalLayout_3.addWidget(self.line_54)
        self.line_55 = QtGui.QFrame(self.frame_3)
        self.line_55.setFrameShape(QtGui.QFrame.HLine)
        self.line_55.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_55.setObjectName(_fromUtf8("line_55"))
        self.verticalLayout_3.addWidget(self.line_55)
        self.line_56 = QtGui.QFrame(self.frame_3)
        self.line_56.setFrameShape(QtGui.QFrame.HLine)
        self.line_56.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_56.setObjectName(_fromUtf8("line_56"))
        self.verticalLayout_3.addWidget(self.line_56)
        self.line_57 = QtGui.QFrame(self.frame_3)
        self.line_57.setFrameShape(QtGui.QFrame.HLine)
        self.line_57.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_57.setObjectName(_fromUtf8("line_57"))
        self.verticalLayout_3.addWidget(self.line_57)
        self.line_58 = QtGui.QFrame(self.frame_3)
        self.line_58.setFrameShape(QtGui.QFrame.HLine)
        self.line_58.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_58.setObjectName(_fromUtf8("line_58"))
        self.verticalLayout_3.addWidget(self.line_58)
        self.line_33 = QtGui.QFrame(self.frame_3)
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.verticalLayout_3.addWidget(self.line_33)
        self.line_59 = QtGui.QFrame(self.frame_3)
        self.line_59.setFrameShape(QtGui.QFrame.HLine)
        self.line_59.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_59.setObjectName(_fromUtf8("line_59"))
        self.verticalLayout_3.addWidget(self.line_59)
        self.line_60 = QtGui.QFrame(self.frame_3)
        self.line_60.setFrameShape(QtGui.QFrame.HLine)
        self.line_60.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_60.setObjectName(_fromUtf8("line_60"))
        self.verticalLayout_3.addWidget(self.line_60)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(420, 30, 100, 650))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line_61 = QtGui.QFrame(self.frame_4)
        self.line_61.setFrameShape(QtGui.QFrame.HLine)
        self.line_61.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_61.setObjectName(_fromUtf8("line_61"))
        self.verticalLayout_4.addWidget(self.line_61)
        self.line_62 = QtGui.QFrame(self.frame_4)
        self.line_62.setFrameShape(QtGui.QFrame.HLine)
        self.line_62.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_62.setObjectName(_fromUtf8("line_62"))
        self.verticalLayout_4.addWidget(self.line_62)
        self.line_63 = QtGui.QFrame(self.frame_4)
        self.line_63.setFrameShape(QtGui.QFrame.HLine)
        self.line_63.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_63.setObjectName(_fromUtf8("line_63"))
        self.verticalLayout_4.addWidget(self.line_63)
        self.line_64 = QtGui.QFrame(self.frame_4)
        self.line_64.setFrameShape(QtGui.QFrame.HLine)
        self.line_64.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_64.setObjectName(_fromUtf8("line_64"))
        self.verticalLayout_4.addWidget(self.line_64)
        self.line_65 = QtGui.QFrame(self.frame_4)
        self.line_65.setFrameShape(QtGui.QFrame.HLine)
        self.line_65.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_65.setObjectName(_fromUtf8("line_65"))
        self.verticalLayout_4.addWidget(self.line_65)
        self.line_66 = QtGui.QFrame(self.frame_4)
        self.line_66.setFrameShape(QtGui.QFrame.HLine)
        self.line_66.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_66.setObjectName(_fromUtf8("line_66"))
        self.verticalLayout_4.addWidget(self.line_66)
        self.line_67 = QtGui.QFrame(self.frame_4)
        self.line_67.setFrameShape(QtGui.QFrame.HLine)
        self.line_67.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_67.setObjectName(_fromUtf8("line_67"))
        self.verticalLayout_4.addWidget(self.line_67)
        self.line_68 = QtGui.QFrame(self.frame_4)
        self.line_68.setFrameShape(QtGui.QFrame.HLine)
        self.line_68.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_68.setObjectName(_fromUtf8("line_68"))
        self.verticalLayout_4.addWidget(self.line_68)
        self.line_34 = QtGui.QFrame(self.frame_4)
        self.line_34.setFrameShape(QtGui.QFrame.HLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.verticalLayout_4.addWidget(self.line_34)
        self.splitter_10 = QtGui.QSplitter(self.centralwidget)
        self.splitter_10.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.lcd1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd1.setGeometry(QtCore.QRect(110, 690, 40, 20))
        self.lcd1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd1.setAutoFillBackground(True)
        self.lcd1.setSmallDecimalPoint(False)
        self.lcd1.setNumDigits(2)
        self.lcd1.setDigitCount(2)
        self.lcd1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd1.setProperty("value", 3.0)
        self.lcd1.setProperty("intValue", 3)
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.splitter_15 = QtGui.QSplitter(self.centralwidget)
        self.splitter_15.setGeometry(QtCore.QRect(200, 720, 80, 80))
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName(_fromUtf8("splitter_15"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_15)
        self.splitter_2.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.EleButton2Up = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton2Up.setFont(font)
        self.EleButton2Up.setObjectName(_fromUtf8("EleButton2Up"))
        self.EleButton2Down = QtGui.QPushButton(self.splitter_2)
        self.EleButton2Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton2Down.setFont(font)
        self.EleButton2Down.setObjectName(_fromUtf8("EleButton2Down"))
        self.splitter_5 = QtGui.QSplitter(self.splitter_15)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.EleButton5Up = QtGui.QPushButton(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton5Up.setFont(font)
        self.EleButton5Up.setObjectName(_fromUtf8("EleButton5Up"))
        self.EleButton5Down = QtGui.QPushButton(self.splitter_5)
        self.EleButton5Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton5Down.setFont(font)
        self.EleButton5Down.setObjectName(_fromUtf8("EleButton5Down"))
        self.splitter_8 = QtGui.QSplitter(self.centralwidget)
        self.splitter_8.setGeometry(QtCore.QRect(370, 740, 80, 80))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_8)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.EleButton3Up = QtGui.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton3Up.setFont(font)
        self.EleButton3Up.setObjectName(_fromUtf8("EleButton3Up"))
        self.EleButton3Down = QtGui.QPushButton(self.splitter_3)
        self.EleButton3Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton3Down.setFont(font)
        self.EleButton3Down.setObjectName(_fromUtf8("EleButton3Down"))
        self.splitter_6 = QtGui.QSplitter(self.splitter_8)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.EleButton6Up = QtGui.QPushButton(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton6Up.setFont(font)
        self.EleButton6Up.setObjectName(_fromUtf8("EleButton6Up"))
        self.EleButton6Down = QtGui.QPushButton(self.splitter_6)
        self.EleButton6Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton6Down.setFont(font)
        self.EleButton6Down.setObjectName(_fromUtf8("EleButton6Down"))
        self.splitter_9 = QtGui.QSplitter(self.centralwidget)
        self.splitter_9.setGeometry(QtCore.QRect(470, 740, 80, 80))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_9)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.EleButton4Up = QtGui.QPushButton(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton4Up.setFont(font)
        self.EleButton4Up.setObjectName(_fromUtf8("EleButton4Up"))
        self.EleButton4Down = QtGui.QPushButton(self.splitter_4)
        self.EleButton4Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton4Down.setFont(font)
        self.EleButton4Down.setObjectName(_fromUtf8("EleButton4Down"))
        self.splitter_7 = QtGui.QSplitter(self.splitter_9)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.EleButton7Up = QtGui.QPushButton(self.splitter_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton7Up.setFont(font)
        self.EleButton7Up.setObjectName(_fromUtf8("EleButton7Up"))
        self.EleButton7Down = QtGui.QPushButton(self.splitter_7)
        self.EleButton7Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton7Down.setFont(font)
        self.EleButton7Down.setObjectName(_fromUtf8("EleButton7Down"))
        self.splitter_13 = QtGui.QSplitter(self.centralwidget)
        self.splitter_13.setGeometry(QtCore.QRect(340, 690, 80, 20))
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName(_fromUtf8("splitter_13"))
        self.lcd3 = QtGui.QLCDNumber(self.splitter_13)
        self.lcd3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd3.setAutoFillBackground(True)
        self.lcd3.setSmallDecimalPoint(False)
        self.lcd3.setNumDigits(2)
        self.lcd3.setDigitCount(2)
        self.lcd3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd3.setProperty("value", 3.0)
        self.lcd3.setProperty("intValue", 3)
        self.lcd3.setObjectName(_fromUtf8("lcd3"))
        self.lcd6 = QtGui.QLCDNumber(self.splitter_13)
        self.lcd6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd6.setAutoFillBackground(True)
        self.lcd6.setSmallDecimalPoint(False)
        self.lcd6.setNumDigits(2)
        self.lcd6.setDigitCount(2)
        self.lcd6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd6.setProperty("value", 3.0)
        self.lcd6.setProperty("intValue", 3)
        self.lcd6.setObjectName(_fromUtf8("lcd6"))
        self.splitter_14 = QtGui.QSplitter(self.centralwidget)
        self.splitter_14.setGeometry(QtCore.QRect(470, 690, 80, 20))
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName(_fromUtf8("splitter_14"))
        self.lcd4 = QtGui.QLCDNumber(self.splitter_14)
        self.lcd4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd4.setAutoFillBackground(True)
        self.lcd4.setSmallDecimalPoint(False)
        self.lcd4.setNumDigits(2)
        self.lcd4.setDigitCount(2)
        self.lcd4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd4.setProperty("value", 3.0)
        self.lcd4.setProperty("intValue", 3)
        self.lcd4.setObjectName(_fromUtf8("lcd4"))
        self.lcd7 = QtGui.QLCDNumber(self.splitter_14)
        self.lcd7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd7.setAutoFillBackground(True)
        self.lcd7.setSmallDecimalPoint(False)
        self.lcd7.setNumDigits(2)
        self.lcd7.setDigitCount(2)
        self.lcd7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd7.setProperty("value", 3.0)
        self.lcd7.setProperty("intValue", 3)
        self.lcd7.setObjectName(_fromUtf8("lcd7"))
        self.splitter_12 = QtGui.QSplitter(self.centralwidget)
        self.splitter_12.setGeometry(QtCore.QRect(200, 690, 74, 23))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName(_fromUtf8("splitter_12"))
        self.lcd2 = QtGui.QLCDNumber(self.splitter_12)
        self.lcd2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd2.setAutoFillBackground(True)
        self.lcd2.setSmallDecimalPoint(False)
        self.lcd2.setNumDigits(2)
        self.lcd2.setDigitCount(2)
        self.lcd2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd2.setProperty("value", 3.0)
        self.lcd2.setProperty("intValue", 3)
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.lcd5 = QtGui.QLCDNumber(self.splitter_12)
        self.lcd5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd5.setAutoFillBackground(True)
        self.lcd5.setSmallDecimalPoint(False)
        self.lcd5.setNumDigits(2)
        self.lcd5.setDigitCount(2)
        self.lcd5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd5.setProperty("value", 3.0)
        self.lcd5.setProperty("intValue", 3)
        self.lcd5.setObjectName(_fromUtf8("lcd5"))
        self.splitter_15.raise_()
        self.splitter_8.raise_()
        self.splitter_9.raise_()
        self.splitter_13.raise_()
        self.splitter_14.raise_()
        self.splitter_12.raise_()
        self.frame_1.raise_()
        self.splitter_1.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.splitter_10.raise_()
        self.lcd1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elevator", None))
        self.EleButton1Up.setText(_translate("MainWindow", "U", None))
        self.EleButton1Down.setText(_translate("MainWindow", "D", None))
        self.EleButton2Up.setText(_translate("MainWindow", "U", None))
        self.EleButton2Down.setText(_translate("MainWindow", "D", None))
        self.EleButton5Up.setText(_translate("MainWindow", "U", None))
        self.EleButton5Down.setText(_translate("MainWindow", "D", None))
        self.EleButton3Up.setText(_translate("MainWindow", "U", None))
        self.EleButton3Down.setText(_translate("MainWindow", "D", None))
        self.EleButton6Up.setText(_translate("MainWindow", "U", None))
        self.EleButton6Down.setText(_translate("MainWindow", "D", None))
        self.EleButton4Up.setText(_translate("MainWindow", "U", None))
        self.EleButton4Down.setText(_translate("MainWindow", "D", None))
        self.EleButton7Up.setText(_translate("MainWindow", "U", None))
        self.EleButton7Down.setText(_translate("MainWindow", "D", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

