# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elev_bak.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1184, 913)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_1 = QtGui.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(90, 30, 100, 650))
        self.frame_1.setFrameShape(QtGui.QFrame.Box)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line = QtGui.QFrame(self.frame_1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.line_2 = QtGui.QFrame(self.frame_1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.line_3 = QtGui.QFrame(self.frame_1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.line_4 = QtGui.QFrame(self.frame_1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.line_5 = QtGui.QFrame(self.frame_1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.line_6 = QtGui.QFrame(self.frame_1)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.line_43 = QtGui.QFrame(self.frame_1)
        self.line_43.setFrameShape(QtGui.QFrame.HLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.verticalLayout.addWidget(self.line_43)
        self.line_31 = QtGui.QFrame(self.frame_1)
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.verticalLayout.addWidget(self.line_31)
        self.line_44 = QtGui.QFrame(self.frame_1)
        self.line_44.setFrameShape(QtGui.QFrame.HLine)
        self.line_44.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_44.setObjectName(_fromUtf8("line_44"))
        self.verticalLayout.addWidget(self.line_44)
        self.splitter_1 = QtGui.QSplitter(self.centralwidget)
        self.splitter_1.setGeometry(QtCore.QRect(100, 740, 80, 80))
        self.splitter_1.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_1.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_1.setLineWidth(1)
        self.splitter_1.setMidLineWidth(0)
        self.splitter_1.setOrientation(QtCore.Qt.Vertical)
        self.splitter_1.setObjectName(_fromUtf8("splitter_1"))
        self.EleButton1Up = QtGui.QPushButton(self.splitter_1)
        self.EleButton1Up.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton1Up.setFont(font)
        self.EleButton1Up.setObjectName(_fromUtf8("EleButton1Up"))
        self.EleButton1Down = QtGui.QPushButton(self.splitter_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton1Down.setFont(font)
        self.EleButton1Down.setObjectName(_fromUtf8("EleButton1Down"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(190, 30, 100, 650))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.line_45 = QtGui.QFrame(self.frame_2)
        self.line_45.setFrameShape(QtGui.QFrame.HLine)
        self.line_45.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_45.setObjectName(_fromUtf8("line_45"))
        self.verticalLayout_2.addWidget(self.line_45)
        self.line_46 = QtGui.QFrame(self.frame_2)
        self.line_46.setFrameShape(QtGui.QFrame.HLine)
        self.line_46.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_46.setObjectName(_fromUtf8("line_46"))
        self.verticalLayout_2.addWidget(self.line_46)
        self.line_32 = QtGui.QFrame(self.frame_2)
        self.line_32.setFrameShape(QtGui.QFrame.HLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.verticalLayout_2.addWidget(self.line_32)
        self.line_47 = QtGui.QFrame(self.frame_2)
        self.line_47.setFrameShape(QtGui.QFrame.HLine)
        self.line_47.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_47.setObjectName(_fromUtf8("line_47"))
        self.verticalLayout_2.addWidget(self.line_47)
        self.line_48 = QtGui.QFrame(self.frame_2)
        self.line_48.setFrameShape(QtGui.QFrame.HLine)
        self.line_48.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_48.setObjectName(_fromUtf8("line_48"))
        self.verticalLayout_2.addWidget(self.line_48)
        self.line_49 = QtGui.QFrame(self.frame_2)
        self.line_49.setFrameShape(QtGui.QFrame.HLine)
        self.line_49.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_49.setObjectName(_fromUtf8("line_49"))
        self.verticalLayout_2.addWidget(self.line_49)
        self.line_50 = QtGui.QFrame(self.frame_2)
        self.line_50.setFrameShape(QtGui.QFrame.HLine)
        self.line_50.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_50.setObjectName(_fromUtf8("line_50"))
        self.verticalLayout_2.addWidget(self.line_50)
        self.line_51 = QtGui.QFrame(self.frame_2)
        self.line_51.setFrameShape(QtGui.QFrame.HLine)
        self.line_51.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_51.setObjectName(_fromUtf8("line_51"))
        self.verticalLayout_2.addWidget(self.line_51)
        self.line_52 = QtGui.QFrame(self.frame_2)
        self.line_52.setFrameShape(QtGui.QFrame.HLine)
        self.line_52.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_52.setObjectName(_fromUtf8("line_52"))
        self.verticalLayout_2.addWidget(self.line_52)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(300, 30, 100, 650))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.line_53 = QtGui.QFrame(self.frame_3)
        self.line_53.setFrameShape(QtGui.QFrame.HLine)
        self.line_53.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_53.setObjectName(_fromUtf8("line_53"))
        self.verticalLayout_3.addWidget(self.line_53)
        self.line_54 = QtGui.QFrame(self.frame_3)
        self.line_54.setFrameShape(QtGui.QFrame.HLine)
        self.line_54.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_54.setObjectName(_fromUtf8("line_54"))
        self.verticalLayout_3.addWidget(self.line_54)
        self.line_55 = QtGui.QFrame(self.frame_3)
        self.line_55.setFrameShape(QtGui.QFrame.HLine)
        self.line_55.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_55.setObjectName(_fromUtf8("line_55"))
        self.verticalLayout_3.addWidget(self.line_55)
        self.line_56 = QtGui.QFrame(self.frame_3)
        self.line_56.setFrameShape(QtGui.QFrame.HLine)
        self.line_56.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_56.setObjectName(_fromUtf8("line_56"))
        self.verticalLayout_3.addWidget(self.line_56)
        self.line_57 = QtGui.QFrame(self.frame_3)
        self.line_57.setFrameShape(QtGui.QFrame.HLine)
        self.line_57.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_57.setObjectName(_fromUtf8("line_57"))
        self.verticalLayout_3.addWidget(self.line_57)
        self.line_58 = QtGui.QFrame(self.frame_3)
        self.line_58.setFrameShape(QtGui.QFrame.HLine)
        self.line_58.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_58.setObjectName(_fromUtf8("line_58"))
        self.verticalLayout_3.addWidget(self.line_58)
        self.line_33 = QtGui.QFrame(self.frame_3)
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.verticalLayout_3.addWidget(self.line_33)
        self.line_59 = QtGui.QFrame(self.frame_3)
        self.line_59.setFrameShape(QtGui.QFrame.HLine)
        self.line_59.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_59.setObjectName(_fromUtf8("line_59"))
        self.verticalLayout_3.addWidget(self.line_59)
        self.line_60 = QtGui.QFrame(self.frame_3)
        self.line_60.setFrameShape(QtGui.QFrame.HLine)
        self.line_60.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_60.setObjectName(_fromUtf8("line_60"))
        self.verticalLayout_3.addWidget(self.line_60)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(420, 30, 100, 650))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line_61 = QtGui.QFrame(self.frame_4)
        self.line_61.setFrameShape(QtGui.QFrame.HLine)
        self.line_61.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_61.setObjectName(_fromUtf8("line_61"))
        self.verticalLayout_4.addWidget(self.line_61)
        self.line_62 = QtGui.QFrame(self.frame_4)
        self.line_62.setFrameShape(QtGui.QFrame.HLine)
        self.line_62.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_62.setObjectName(_fromUtf8("line_62"))
        self.verticalLayout_4.addWidget(self.line_62)
        self.line_63 = QtGui.QFrame(self.frame_4)
        self.line_63.setFrameShape(QtGui.QFrame.HLine)
        self.line_63.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_63.setObjectName(_fromUtf8("line_63"))
        self.verticalLayout_4.addWidget(self.line_63)
        self.line_64 = QtGui.QFrame(self.frame_4)
        self.line_64.setFrameShape(QtGui.QFrame.HLine)
        self.line_64.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_64.setObjectName(_fromUtf8("line_64"))
        self.verticalLayout_4.addWidget(self.line_64)
        self.line_65 = QtGui.QFrame(self.frame_4)
        self.line_65.setFrameShape(QtGui.QFrame.HLine)
        self.line_65.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_65.setObjectName(_fromUtf8("line_65"))
        self.verticalLayout_4.addWidget(self.line_65)
        self.line_66 = QtGui.QFrame(self.frame_4)
        self.line_66.setFrameShape(QtGui.QFrame.HLine)
        self.line_66.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_66.setObjectName(_fromUtf8("line_66"))
        self.verticalLayout_4.addWidget(self.line_66)
        self.line_67 = QtGui.QFrame(self.frame_4)
        self.line_67.setFrameShape(QtGui.QFrame.HLine)
        self.line_67.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_67.setObjectName(_fromUtf8("line_67"))
        self.verticalLayout_4.addWidget(self.line_67)
        self.line_68 = QtGui.QFrame(self.frame_4)
        self.line_68.setFrameShape(QtGui.QFrame.HLine)
        self.line_68.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_68.setObjectName(_fromUtf8("line_68"))
        self.verticalLayout_4.addWidget(self.line_68)
        self.line_34 = QtGui.QFrame(self.frame_4)
        self.line_34.setFrameShape(QtGui.QFrame.HLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.verticalLayout_4.addWidget(self.line_34)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(550, 30, 100, 650))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setLineWidth(1)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.line_69 = QtGui.QFrame(self.frame_5)
        self.line_69.setFrameShape(QtGui.QFrame.HLine)
        self.line_69.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_69.setObjectName(_fromUtf8("line_69"))
        self.verticalLayout_5.addWidget(self.line_69)
        self.line_70 = QtGui.QFrame(self.frame_5)
        self.line_70.setFrameShape(QtGui.QFrame.HLine)
        self.line_70.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_70.setObjectName(_fromUtf8("line_70"))
        self.verticalLayout_5.addWidget(self.line_70)
        self.line_71 = QtGui.QFrame(self.frame_5)
        self.line_71.setFrameShape(QtGui.QFrame.HLine)
        self.line_71.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_71.setObjectName(_fromUtf8("line_71"))
        self.verticalLayout_5.addWidget(self.line_71)
        self.line_72 = QtGui.QFrame(self.frame_5)
        self.line_72.setFrameShape(QtGui.QFrame.HLine)
        self.line_72.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_72.setObjectName(_fromUtf8("line_72"))
        self.verticalLayout_5.addWidget(self.line_72)
        self.line_73 = QtGui.QFrame(self.frame_5)
        self.line_73.setFrameShape(QtGui.QFrame.HLine)
        self.line_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_73.setObjectName(_fromUtf8("line_73"))
        self.verticalLayout_5.addWidget(self.line_73)
        self.line_74 = QtGui.QFrame(self.frame_5)
        self.line_74.setFrameShape(QtGui.QFrame.HLine)
        self.line_74.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_74.setObjectName(_fromUtf8("line_74"))
        self.verticalLayout_5.addWidget(self.line_74)
        self.line_75 = QtGui.QFrame(self.frame_5)
        self.line_75.setFrameShape(QtGui.QFrame.HLine)
        self.line_75.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_75.setObjectName(_fromUtf8("line_75"))
        self.verticalLayout_5.addWidget(self.line_75)
        self.line_35 = QtGui.QFrame(self.frame_5)
        self.line_35.setFrameShape(QtGui.QFrame.HLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.verticalLayout_5.addWidget(self.line_35)
        self.line_76 = QtGui.QFrame(self.frame_5)
        self.line_76.setFrameShape(QtGui.QFrame.HLine)
        self.line_76.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_76.setObjectName(_fromUtf8("line_76"))
        self.verticalLayout_5.addWidget(self.line_76)
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(650, 20, 150, 650))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setLineWidth(1)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.line_36 = QtGui.QFrame(self.frame_6)
        self.line_36.setFrameShape(QtGui.QFrame.HLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.verticalLayout_6.addWidget(self.line_36)
        self.line_77 = QtGui.QFrame(self.frame_6)
        self.line_77.setFrameShape(QtGui.QFrame.HLine)
        self.line_77.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_77.setObjectName(_fromUtf8("line_77"))
        self.verticalLayout_6.addWidget(self.line_77)
        self.line_78 = QtGui.QFrame(self.frame_6)
        self.line_78.setFrameShape(QtGui.QFrame.HLine)
        self.line_78.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_78.setObjectName(_fromUtf8("line_78"))
        self.verticalLayout_6.addWidget(self.line_78)
        self.line_79 = QtGui.QFrame(self.frame_6)
        self.line_79.setFrameShape(QtGui.QFrame.HLine)
        self.line_79.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_79.setObjectName(_fromUtf8("line_79"))
        self.verticalLayout_6.addWidget(self.line_79)
        self.line_80 = QtGui.QFrame(self.frame_6)
        self.line_80.setFrameShape(QtGui.QFrame.HLine)
        self.line_80.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_80.setObjectName(_fromUtf8("line_80"))
        self.verticalLayout_6.addWidget(self.line_80)
        self.line_81 = QtGui.QFrame(self.frame_6)
        self.line_81.setFrameShape(QtGui.QFrame.HLine)
        self.line_81.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_81.setObjectName(_fromUtf8("line_81"))
        self.verticalLayout_6.addWidget(self.line_81)
        self.line_82 = QtGui.QFrame(self.frame_6)
        self.line_82.setFrameShape(QtGui.QFrame.HLine)
        self.line_82.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_82.setObjectName(_fromUtf8("line_82"))
        self.verticalLayout_6.addWidget(self.line_82)
        self.line_83 = QtGui.QFrame(self.frame_6)
        self.line_83.setFrameShape(QtGui.QFrame.HLine)
        self.line_83.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_83.setObjectName(_fromUtf8("line_83"))
        self.verticalLayout_6.addWidget(self.line_83)
        self.line_84 = QtGui.QFrame(self.frame_6)
        self.line_84.setFrameShape(QtGui.QFrame.HLine)
        self.line_84.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_84.setObjectName(_fromUtf8("line_84"))
        self.verticalLayout_6.addWidget(self.line_84)
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(870, 70, 91, 551))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setLineWidth(1)
        self.frame_7.setMidLineWidth(0)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.line_86 = QtGui.QFrame(self.frame_7)
        self.line_86.setFrameShape(QtGui.QFrame.HLine)
        self.line_86.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_86.setObjectName(_fromUtf8("line_86"))
        self.verticalLayout_7.addWidget(self.line_86)
        self.line_85 = QtGui.QFrame(self.frame_7)
        self.line_85.setFrameShape(QtGui.QFrame.HLine)
        self.line_85.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_85.setObjectName(_fromUtf8("line_85"))
        self.verticalLayout_7.addWidget(self.line_85)
        self.line_87 = QtGui.QFrame(self.frame_7)
        self.line_87.setFrameShape(QtGui.QFrame.HLine)
        self.line_87.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_87.setObjectName(_fromUtf8("line_87"))
        self.verticalLayout_7.addWidget(self.line_87)
        self.line_88 = QtGui.QFrame(self.frame_7)
        self.line_88.setFrameShape(QtGui.QFrame.HLine)
        self.line_88.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_88.setObjectName(_fromUtf8("line_88"))
        self.verticalLayout_7.addWidget(self.line_88)
        self.line_89 = QtGui.QFrame(self.frame_7)
        self.line_89.setFrameShape(QtGui.QFrame.HLine)
        self.line_89.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_89.setObjectName(_fromUtf8("line_89"))
        self.verticalLayout_7.addWidget(self.line_89)
        self.line_90 = QtGui.QFrame(self.frame_7)
        self.line_90.setFrameShape(QtGui.QFrame.HLine)
        self.line_90.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_90.setObjectName(_fromUtf8("line_90"))
        self.verticalLayout_7.addWidget(self.line_90)
        self.line_92 = QtGui.QFrame(self.frame_7)
        self.line_92.setFrameShape(QtGui.QFrame.HLine)
        self.line_92.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_92.setObjectName(_fromUtf8("line_92"))
        self.verticalLayout_7.addWidget(self.line_92)
        self.line_91 = QtGui.QFrame(self.frame_7)
        self.line_91.setFrameShape(QtGui.QFrame.HLine)
        self.line_91.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_91.setObjectName(_fromUtf8("line_91"))
        self.verticalLayout_7.addWidget(self.line_91)
        self.line_37 = QtGui.QFrame(self.frame_7)
        self.line_37.setFrameShape(QtGui.QFrame.HLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.verticalLayout_7.addWidget(self.line_37)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(250, 740, 80, 80))
        self.splitter_2.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.EleButton2Up = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton2Up.setFont(font)
        self.EleButton2Up.setObjectName(_fromUtf8("EleButton2Up"))
        self.EleButton2Down = QtGui.QPushButton(self.splitter_2)
        self.EleButton2Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton2Down.setFont(font)
        self.EleButton2Down.setObjectName(_fromUtf8("EleButton2Down"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(380, 750, 80, 80))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.EleButton3Up = QtGui.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton3Up.setFont(font)
        self.EleButton3Up.setObjectName(_fromUtf8("EleButton3Up"))
        self.EleButton3Down = QtGui.QPushButton(self.splitter_3)
        self.EleButton3Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton3Down.setFont(font)
        self.EleButton3Down.setObjectName(_fromUtf8("EleButton3Down"))
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(460, 760, 80, 80))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.EleButton4Up = QtGui.QPushButton(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton4Up.setFont(font)
        self.EleButton4Up.setObjectName(_fromUtf8("EleButton4Up"))
        self.EleButton4Down = QtGui.QPushButton(self.splitter_4)
        self.EleButton4Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton4Down.setFont(font)
        self.EleButton4Down.setObjectName(_fromUtf8("EleButton4Down"))
        self.splitter_5 = QtGui.QSplitter(self.centralwidget)
        self.splitter_5.setGeometry(QtCore.QRect(570, 750, 80, 80))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.EleButton5Up = QtGui.QPushButton(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton5Up.setFont(font)
        self.EleButton5Up.setObjectName(_fromUtf8("EleButton5Up"))
        self.EleButton5Down = QtGui.QPushButton(self.splitter_5)
        self.EleButton5Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton5Down.setFont(font)
        self.EleButton5Down.setObjectName(_fromUtf8("EleButton5Down"))
        self.splitter_7 = QtGui.QSplitter(self.centralwidget)
        self.splitter_7.setGeometry(QtCore.QRect(880, 750, 80, 80))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.EleButton7Up = QtGui.QPushButton(self.splitter_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton7Up.setFont(font)
        self.EleButton7Up.setObjectName(_fromUtf8("EleButton7Up"))
        self.EleButton7Down = QtGui.QPushButton(self.splitter_7)
        self.EleButton7Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton7Down.setFont(font)
        self.EleButton7Down.setObjectName(_fromUtf8("EleButton7Down"))
        self.splitter_10 = QtGui.QSplitter(self.centralwidget)
        self.splitter_10.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.splitter_6 = QtGui.QSplitter(self.centralwidget)
        self.splitter_6.setGeometry(QtCore.QRect(730, 770, 80, 80))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.EleButton6Up = QtGui.QPushButton(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton6Up.setFont(font)
        self.EleButton6Up.setObjectName(_fromUtf8("EleButton6Up"))
        self.EleButton6Down = QtGui.QPushButton(self.splitter_6)
        self.EleButton6Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton6Down.setFont(font)
        self.EleButton6Down.setObjectName(_fromUtf8("EleButton6Down"))
        self.lcd1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd1.setGeometry(QtCore.QRect(110, 690, 50, 20))
        self.lcd1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd1.setAutoFillBackground(True)
        self.lcd1.setSmallDecimalPoint(False)
        self.lcd1.setNumDigits(2)
        self.lcd1.setDigitCount(2)
        self.lcd1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd1.setProperty("value", 3.0)
        self.lcd1.setProperty("intValue", 3)
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.lcd2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd2.setGeometry(QtCore.QRect(210, 690, 50, 20))
        self.lcd2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd2.setAutoFillBackground(True)
        self.lcd2.setSmallDecimalPoint(False)
        self.lcd2.setNumDigits(2)
        self.lcd2.setDigitCount(2)
        self.lcd2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd2.setProperty("value", 3.0)
        self.lcd2.setProperty("intValue", 3)
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.lcd3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd3.setGeometry(QtCore.QRect(320, 690, 50, 20))
        self.lcd3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd3.setAutoFillBackground(True)
        self.lcd3.setSmallDecimalPoint(False)
        self.lcd3.setNumDigits(2)
        self.lcd3.setDigitCount(2)
        self.lcd3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd3.setProperty("value", 3.0)
        self.lcd3.setProperty("intValue", 3)
        self.lcd3.setObjectName(_fromUtf8("lcd3"))
        self.lcd4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd4.setGeometry(QtCore.QRect(420, 690, 50, 20))
        self.lcd4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd4.setAutoFillBackground(True)
        self.lcd4.setSmallDecimalPoint(False)
        self.lcd4.setNumDigits(2)
        self.lcd4.setDigitCount(2)
        self.lcd4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd4.setProperty("value", 3.0)
        self.lcd4.setProperty("intValue", 3)
        self.lcd4.setObjectName(_fromUtf8("lcd4"))
        self.lcd5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd5.setGeometry(QtCore.QRect(520, 690, 50, 20))
        self.lcd5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd5.setAutoFillBackground(True)
        self.lcd5.setSmallDecimalPoint(False)
        self.lcd5.setNumDigits(2)
        self.lcd5.setDigitCount(2)
        self.lcd5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd5.setProperty("value", 3.0)
        self.lcd5.setProperty("intValue", 3)
        self.lcd5.setObjectName(_fromUtf8("lcd5"))
        self.lcd6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd6.setGeometry(QtCore.QRect(620, 690, 50, 20))
        self.lcd6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd6.setAutoFillBackground(True)
        self.lcd6.setSmallDecimalPoint(False)
        self.lcd6.setNumDigits(2)
        self.lcd6.setDigitCount(2)
        self.lcd6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd6.setProperty("value", 3.0)
        self.lcd6.setProperty("intValue", 3)
        self.lcd6.setObjectName(_fromUtf8("lcd6"))
        self.lcd7 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd7.setGeometry(QtCore.QRect(720, 690, 50, 20))
        self.lcd7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd7.setAutoFillBackground(True)
        self.lcd7.setSmallDecimalPoint(False)
        self.lcd7.setNumDigits(2)
        self.lcd7.setDigitCount(2)
        self.lcd7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd7.setProperty("value", 3.0)
        self.lcd7.setProperty("intValue", 3)
        self.lcd7.setObjectName(_fromUtf8("lcd7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elevator", None))
        self.EleButton1Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton1Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton2Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton2Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton3Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton3Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton4Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton4Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton5Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton5Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton7Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton7Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton6Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton6Down.setText(_translate("MainWindow", "Down", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

