# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elev.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.EleWell1 = QtGui.QFrame(self.centralwidget)
        self.EleWell1.setGeometry(QtCore.QRect(100, 50, 97, 651))
        self.EleWell1.setFrameShape(QtGui.QFrame.WinPanel)
        self.EleWell1.setFrameShadow(QtGui.QFrame.Sunken)
        self.EleWell1.setObjectName(_fromUtf8("EleWell1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.EleWell1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line = QtGui.QFrame(self.EleWell1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.line_2 = QtGui.QFrame(self.EleWell1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.line_3 = QtGui.QFrame(self.EleWell1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.line_4 = QtGui.QFrame(self.EleWell1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.line_5 = QtGui.QFrame(self.EleWell1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.line_6 = QtGui.QFrame(self.EleWell1)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.EleButton1Up = QtGui.QPushButton(self.EleWell1)
        self.EleButton1Up.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton1Up.setFont(font)
        self.EleButton1Up.setObjectName(_fromUtf8("EleButton1Up"))
        self.verticalLayout.addWidget(self.EleButton1Up)
        self.EleButton1Down = QtGui.QPushButton(self.EleWell1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton1Down.setFont(font)
        self.EleButton1Down.setObjectName(_fromUtf8("EleButton1Down"))
        self.verticalLayout.addWidget(self.EleButton1Down)
        self.EleWell2 = QtGui.QFrame(self.centralwidget)
        self.EleWell2.setGeometry(QtCore.QRect(270, 50, 100, 650))
        self.EleWell2.setFrameShape(QtGui.QFrame.WinPanel)
        self.EleWell2.setFrameShadow(QtGui.QFrame.Sunken)
        self.EleWell2.setObjectName(_fromUtf8("EleWell2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.EleWell2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.line_7 = QtGui.QFrame(self.EleWell2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_2.addWidget(self.line_7)
        self.line_8 = QtGui.QFrame(self.EleWell2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_2.addWidget(self.line_8)
        self.line_9 = QtGui.QFrame(self.EleWell2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_2.addWidget(self.line_9)
        self.line_10 = QtGui.QFrame(self.EleWell2)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_2.addWidget(self.line_10)
        self.line_11 = QtGui.QFrame(self.EleWell2)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_2.addWidget(self.line_11)
        self.line_12 = QtGui.QFrame(self.EleWell2)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_2.addWidget(self.line_12)
        self.EleButton2Up = QtGui.QPushButton(self.EleWell2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton2Up.setFont(font)
        self.EleButton2Up.setObjectName(_fromUtf8("EleButton2Up"))
        self.verticalLayout_2.addWidget(self.EleButton2Up)
        self.EleButton2Down = QtGui.QPushButton(self.EleWell2)
        self.EleButton2Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton2Down.setFont(font)
        self.EleButton2Down.setObjectName(_fromUtf8("EleButton2Down"))
        self.verticalLayout_2.addWidget(self.EleButton2Down)
        self.EleWell3 = QtGui.QFrame(self.centralwidget)
        self.EleWell3.setGeometry(QtCore.QRect(440, 50, 100, 650))
        self.EleWell3.setFrameShape(QtGui.QFrame.WinPanel)
        self.EleWell3.setFrameShadow(QtGui.QFrame.Sunken)
        self.EleWell3.setObjectName(_fromUtf8("EleWell3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.EleWell3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.line_13 = QtGui.QFrame(self.EleWell3)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_3.addWidget(self.line_13)
        self.line_14 = QtGui.QFrame(self.EleWell3)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.verticalLayout_3.addWidget(self.line_14)
        self.line_15 = QtGui.QFrame(self.EleWell3)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.verticalLayout_3.addWidget(self.line_15)
        self.line_16 = QtGui.QFrame(self.EleWell3)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.verticalLayout_3.addWidget(self.line_16)
        self.line_17 = QtGui.QFrame(self.EleWell3)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.verticalLayout_3.addWidget(self.line_17)
        self.line_18 = QtGui.QFrame(self.EleWell3)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.verticalLayout_3.addWidget(self.line_18)
        self.EleButton3Up = QtGui.QPushButton(self.EleWell3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton3Up.setFont(font)
        self.EleButton3Up.setObjectName(_fromUtf8("EleButton3Up"))
        self.verticalLayout_3.addWidget(self.EleButton3Up)
        self.EleButton3Down = QtGui.QPushButton(self.EleWell3)
        self.EleButton3Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton3Down.setFont(font)
        self.EleButton3Down.setObjectName(_fromUtf8("EleButton3Down"))
        self.verticalLayout_3.addWidget(self.EleButton3Down)
        self.EleWell4 = QtGui.QFrame(self.centralwidget)
        self.EleWell4.setGeometry(QtCore.QRect(600, 50, 100, 650))
        self.EleWell4.setFrameShape(QtGui.QFrame.WinPanel)
        self.EleWell4.setFrameShadow(QtGui.QFrame.Sunken)
        self.EleWell4.setObjectName(_fromUtf8("EleWell4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.EleWell4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line_19 = QtGui.QFrame(self.EleWell4)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.verticalLayout_4.addWidget(self.line_19)
        self.line_20 = QtGui.QFrame(self.EleWell4)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.verticalLayout_4.addWidget(self.line_20)
        self.line_21 = QtGui.QFrame(self.EleWell4)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.verticalLayout_4.addWidget(self.line_21)
        self.line_22 = QtGui.QFrame(self.EleWell4)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.verticalLayout_4.addWidget(self.line_22)
        self.line_23 = QtGui.QFrame(self.EleWell4)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.verticalLayout_4.addWidget(self.line_23)
        self.line_24 = QtGui.QFrame(self.EleWell4)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.verticalLayout_4.addWidget(self.line_24)
        self.EleButton4Up = QtGui.QPushButton(self.EleWell4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton4Up.setFont(font)
        self.EleButton4Up.setObjectName(_fromUtf8("EleButton4Up"))
        self.verticalLayout_4.addWidget(self.EleButton4Up)
        self.EleButton4Down = QtGui.QPushButton(self.EleWell4)
        self.EleButton4Down.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.EleButton4Down.setFont(font)
        self.EleButton4Down.setObjectName(_fromUtf8("EleButton4Down"))
        self.verticalLayout_4.addWidget(self.EleButton4Down)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elevator", None))
        self.EleButton1Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton1Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton2Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton2Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton3Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton3Down.setText(_translate("MainWindow", "Down", None))
        self.EleButton4Up.setText(_translate("MainWindow", "Up", None))
        self.EleButton4Down.setText(_translate("MainWindow", "Down", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
